---
- name: install marathon
  yum: pkg=marathon state=latest

- name: configure containerizers
  lineinfile: dest=/etc/mesos-slave/containerizers create=yes line="docker,mesos"

- name: start mesos-master
  service: name=mesos-master state=started enabled=yes

- name: start marathon
  service: name=marathon state=started enabled=yes

- name: start docker
  service: name=docker state=started enabled=yes