---
- name: install marathon
  yum: pkg=marathon state=latest

- name: configure containerizers
  lineinfile: dest=/etc/mesos-slave/containerizers create=yes line="docker,mesos"

- name: start mesos-master
  service: name=mesos-master state=started enabled=yes

- name: start marathon
  service: name=marathon state=started enabled=yes

- name: start chronos
  service: name=chronos state=started enabled=yes

- name: start docker
  service: name=docker state=started enabled=yes

# Mesos-DNS
- name: install go, git, and dnsutil packages
  yum: pkg=golang,git,bind-utils state=latest

- name: build/configure mesos-dns
  become_user: vagrant
  shell: sh /vagrant/ansible/roles/mesos_master/files/install_mesos_dns.sh

- name: map cluster nodes to their names
  template: src=mesos-dns-config.json.j2 dest=/home/vagrant/config.json

- name: create mesos-dns app in Marathon
  uri:
    url: http://{{ ip }}:8080/v2/apps
    method: POST
    body: "{{ lookup('file','marathon-create-mesos-dns-app.json') }}"
    body_format: json
    # not the best idea to treat 409 (Conflict) as Success, but task needs to be indepotent. Could be done better though.
    status_code: 200, 409
    HEADER_Content-Type: "application/json; charset=utf-8"

# Chronos
- name: install chronos
  yum: pkg=chronos state=latest

- name: create mesos-dns app in Marathon
  uri:
    url: http://{{ ip }}:8080/v2/apps
    method: POST
    body: "{{ lookup('file','marathon-create-chronos-app.json') }}"
    body_format: json
    status_code: 200, 409 # OK or Conflict (app already exists)
    HEADER_Content-Type: "application/json; charset=utf-8"

- name: Add Mesos-DNS to resolv.conf
  lineinfile: dest=/etc/resolv.conf
              line="nameserver {{ hostvars['node1']['ip'] }}"
              state=present